name: Go Test

on:
  push:
    paths:
      - "**.go"
      - "Makefile"
      - "go.mod"
      - "go.sum"

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      with:
        go-version: "^1.17"
      - run: make test
