name: Go Test

on:
  push:
    paths:
      - "**.go"
      - "Makefile"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/**"
      - "**.sh"

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: "test"
        run: make test
      - name: "benchmark"
        run: make bench
